### PR TITLE
Final leaflet map

### PR DESCRIPTION
**Pull request by steffilazerte**
Here is the first draft of the leaflet map. I've made a couple of changes and there are some formatting differences between this map and the one [here](http://www.env.gov.bc.ca/soe/indicators/air/ozone_viz/index.html#):

## Changes (Deliberately made different)
- Added slight increase in opacity of the polygons on mouse hover (makes it clear which polygon is selected - we could do something similar for the markers too)
- Created new svg markers (they don't have a circle in the middle, let me know if you would like them formatted differently)
- I left space between the legend colour boxes
- Map dimensions are fixed in width, but the height varies with the window height

## Differences (Harder to make the same)
- Instead of modal windows to show the figures, I've used the popup windows which can be created with leaflet for R. This means that the windows aren't fixed in place and move with scrolling. If the popup is at the bottom of the map, it may be covered by the legends. Because of the way leaflet for R creates the different map layers, it isn't possible (as far as I can tell) to make this popup pane fixed in position (because it is a child element of the map itself, not a sibling).
- Home zoom button is below the zoom in/out buttons (instead of above)

## Questions
- I created the data by running the scripts here, but which version of rcaaqs should I be using? The one in bcgov/rcaaqs master or the dev-steffi? It might not make a difference, but just in case...
- Right now I can't see how "Insufficient Data" at the Station Scale is depicted (is it just omitted?) Is this something you want to include?
- I have matched the formatting as much as possible, but can only match the colours that are present in the current maps. Since there are no stations/airzones that area actually Not Achieved I don't know the exact shade of pink/red used to colour the Status Box in the popup. I've designated it the same colour as the Airzone shading (pinkish), but I think it would have originally been a bit darker. Do you have the original colours used?

## Comments
- I do some extra formatting in the script to make the legend units match the original map, and I also calculate the number of stations per airzone. These changes could perhaps be better placed in the scripts that make the data in the first place (so to keep this map script as specific to mapping as possible).

**Next, I'll start on the pm2.5, but since most of the formatting will be the same, I'll wait until you're satisfied with the general formatting of this map, first.**

### CODE REVIEW

**Comment by ateucher** [comment]
Hi @steffilazerte - looking good!

To the points you outlined on differences from the original map:
- I like the opacity increase on hover
- svg markers look good, but can you make the stroke a bit thinner (and maybe dark grey instead of black)?
- Regarding floating popups vs modals, that's no problem. I think you can use the `autoPanPaddingTopLeft` and `autoPanPaddingBottomRight` arguments in `popupOptions()` to get it to popup relatively consistently.
- All else is fine - the home button is nice, and just fine below rather than above.
- I think the height of the window should be fixed too. Since we will be including it in another page via an iFrame a predictable height and width is helpful.

To your questions:
- I think it makes sense to run the data using the `dev-steffi` branch.
- Insufficient data - There is one station in PM2.5 that has insufficient data (Creston in the SE) which you can use as a template for the popup. We should come up with a map icon that denotes insufficient data - ideas welcome!
- The colour we currently use for the 'not achieved' box is `#B8373E`.

To your comment:
- I'll leave it up to you to edit the existing scripts to make the workflow the most efficient, so please feel free to do what you need.

A couple of other comments:
- The line charts did not show up in the popup windows for me. I'm not 100% sure why, but since they are in the `out` folder one level higher than the leaflet folder, they probably aren't being referenced properly. Can you localize/embed them a bit more so that it is more self-contained? I think this could be done simply by including the `station_plots` folder in the leaflet folder.
- If you're editing the scripts to adjust the outputs, I think you could omit the writing of the `airzones.geojson` file and use `bcmaps::bc_airzones()`?

**Comment by ateucher** [comment]
Oh, one more thing. We don't generally commit the rendered html, so can you please remove it?

**Comment by steffilazerte** [comment]
Thanks for the feedback, I'll let you know how it goes. I've removed the html file, would you like me to purge it too?

**Comment by ateucher** [comment]
Great, thanks. No, you don't need to remove it from the git history.

**Comment by stephhazlitt** [comment]
This is looking great @steffilazerte, thanks for your work so far. I like your 'slight increase in opacity of the polygons on mouse hover ' enhancement, it would be great if you could replicate for the markers, as you suggest above.

**Comment by steffilazerte** [comment]
I've been thinking about what to do with the insufficient data markers. These are the ideas I've come up with, let me know what you think!

1) New colours. Re-do the colouring on the markers to match that of the polygons (i.e. blue to pink for CAAQS, grey for missing)
2) No colour. Only outline of a marker
3) Omit the marker
4) Add colour. Keep the grey scale, but add an extra colour to define missing (perhaps pale yellow?) The problem with this is that it draws a lot of attention to these markers.

We could also toy around with adding/removing icons (as in the original) or changing the opacity, but the problem is that the marker still has to have a base colour which shouldn't match a colour with information.

**Comment by stephhazlitt** [comment]
If I understand correctly, the use case for the insufficient data marker is specific to fine particulate matter where two CAAQS metrics are reported&mdash;in some situations there can be sufficient data for one metric but not the other? If this is the case, I am thinking that option 3, omitting the marker, might be the most consistent with the overall design of the indicator (only stations that meet the data sufficiency criteria are reported)?

**Comment by steffilazerte** [comment]
That's right, currently the only use case is for that one station. But I assumed you would want these scripts generalized to future years, where there might be more cases with missing stations (?).

Option 3 is definitely one of the simpler ones :)

**Comment by stephhazlitt** [comment]
Hi @steffilazerte & @ateucher. I reviewed the [Guidance Document on Achievement Determination: Canadian Ambient Air Quality Standards for Fine Particulate Matter and Ozone (2012)](https://www.ccme.ca/files/Resources/air/aqms/pn_1483_gdad_eng.pdf) and confirmed with our subject matter expert&mdash;if only one of two metrics is available, then only one metric is reported. Options are consistent with your design suggestions, not showing the marker for those or having an NA marker. I lean to Option 3 since the maps are stand-alone products, where a user will be viewing results for one metric at a time and not likely comparing side-by-side? If the results were presented in a table format then I think an NA is useful.

**Comment by steffilazerte** [comment]
+1 for Option 3, as it is simpler to implement and matches the original map

**Comment by ateucher** [comment]
I'm on board! Thanks both :)

**Comment by steffilazerte** [comment]
Okay,  I've made the formatting edits:
- I've added a fixed window height of 700px
- SVG marker outlines are less intense (grey and thinner)
- Popups are now padded to appear in the upper half of the map (these exact padding numbers will have to be changed if the fixed window height changes)
- Polygon legend has been moved to the lower right corner to avoid overlapping the popups (it's not possible to put them on the layer below the popups, unfortunately)
- Stations with Insufficient Data are removed (but are included in the "number of stations count" for the Airzone tooltips)
- The line charts are now correctly referenced (but not embedded)
- I added info to the assets/ folder for how the svg markers were made (in case they need to be edited in the future)
- I also added an alpha change on the marker mouse over. I'm not trilled with it, but let me know what you think. Because the markers are grey scale, I don't really think the alpha gives much extra, unfortunately.

I didn't end up running the data output with the new rcaaqs, because the new rcaaqs is too different. In the end I also decided not to edit the original output scripts because they rely on the original rcaaqs script. If the new rcaaqs is to be used in the future, I don't think it's worth making the changes.

I've applied all of these formats to the pm2.5 indicator as well, with some minor changes (discussed in that pull request)

**Comment by ateucher** [comment]
Hi @steffilazerte,

This looks great, thank you! I hope you don't mind, I pushed a small change to put the plots in the same folder as the html file so that it is easier to grab the whole thing and drop it into our website and have the relative image paths work.

I think this is 99% there. 

Regarding the alpha, I agree it doesn't change much. It also made me wonder if they will look darker than they actually are if the markers are stacked (as they are when they are zoomed out)?

I have one other request if you can - is it possible to recenter the map when a user closes the popup window?

**Comment by steffilazerte** [comment]
No problem, that makes sense regarding the figures. I was thinking in terms of what you need to get INTO the script, but it makes sense to group what you need to get OUT of it!

I will look into the recentring... I think it should be possible, but I'll have to look into how precisely to have it work out.

**Comment by stephhazlitt** [comment]
Great work on this, thank you. 

Is it possible to have the polygon with 0 monitoring stations (or insufficient data) _not_ open a modal window on click (that is the [current design](http://www.env.gov.bc.ca/soe/indicators/air/ozone.html))?

**Comment by steffilazerte** [comment]
Ack! Good point. I added that to the pm2.5 but forgot to add it to the ozone. 

Oh and what's the verdict for the markers? Remove the alpha on hover, or leave them as is?

**Comment by ateucher** [comment]
For the markers, I think the short version is to remove the alpha on hover. 

There's another potential issue there, in that the markers steal focus on hover, so the underlying polygon loses its highlighting when you hover over a marker. Is there any way to avoid that? It's a bit jarring, especially when you're zoomed in to an area where there's a cluster of markers and you're going in and out of the the polygon as you hover over the markers the background flashes in and out. 

If that's not possible (or relatively straightforward), I wonder if we should remove the highlighting on the polygons as well?

**Comment by steffilazerte** [comment]
I'm pretty sure that it's not going to straightforward to keep the alpha change on the polygon while hovering over a marker unless I change the method (I use CSS styling with the 'hover' attribute). 

However, I would argue that this is actually a good thing as it becomes an indication of having 'selected' a marker, so that the user knows that if they click, it's now on a marker, and not on the polygon.

**Comment by ateucher** [comment]
> I'm pretty sure that it's not going to straightforward to keep the alpha change on the polygon while hovering over a marker unless I change the method (I use CSS styling with the 'hover' attribute).

I figured that was probably the case.

> an indication of having 'selected' a marker, so that the user knows that if they click, it's now on a marker, and not on the polygon

I think this is also conveyed by the tooltip changing... @stephhazlitt what do you think?

**Comment by stephhazlitt** [comment]
Having a feature that lets the user know where they are before clicking is super helpful. This information is being conveyed by both the tooltip and the polygon/marker highlighting. While I like both at the provincial-scale, I am personally finding it visually challenging at the airzone or station-scale. The polygon highlighting&mdash;when it flickers as the mouse moves past stations&mdash;pulls my eyes away from the tooltip, and the tooltip tells me which station I am on re: clicking. For me, even though I usually know the general region or area of the station I am after, it often takes a few hovers & reading the tooltip before I get the target station.

I say pick a path. Either way&mdash;if you remove the current highlighting or stick with it&mdash;leave the scripts well commented. We can test run the highlighting with some users and decide the end product based on user feedback? Maybe I am just easily distracted 🤷.

**Comment by steffilazerte** [comment]
Good idea, I'll comment it out and if things change down the line you can always add it back in!

**Comment by steffilazerte** [comment]
Okay, I think I've implemented all the changes, let me know what you think!

With respect to markers and polygon alpha, if you want to change it later down the road, you'll have to look in different places, depending on the object:
- **Polygon** alpha is controlled in the addPolygon() function (for example using `highlightOptions = highlightOptions(fillOpacity = 0.7)`
- **Marker** alpha is controlled through css with the hover selector ([for example](https://github.com/steffilazerte/ozone-caaqs-indicator/blob/555d4d0257aa9442c2fc1a67af02d8ed24dc2159/leaflet_map/assets/styles.css#L117))

**Comment by ateucher** [comment]
This looks great, and thank you for the commenting in the code. As with the pm2.5 viz, we will give this one more deeper look, but as it stands it looks very good.

**Pull request merged**
